# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mixtral.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmixtral.proto\"+\n\x02Id\x12\x14\n\x0c\x63onversation\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\x05\"U\n\x07Request\x12\x0f\n\x02id\x18\x01 \x01(\x0b\x32\x03.Id\x12\r\n\x05query\x18\x02 \x01(\t\x12\x1b\n\nmax_tokens\x18\x03 \x01(\x05\x42\x02\x18\x01H\x00\x88\x01\x01\x42\r\n\x0b_max_tokens\"<\n\x08Response\x12\x0f\n\x02id\x18\x01 \x01(\x0b\x32\x03.Id\x12\r\n\x05query\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x01(\t2s\n\x07\x43\x61llLLM\x12\x1e\n\x05Plain\x12\x08.Request\x1a\t.Response\"\x00\x12$\n\x0b\x45xplainWord\x12\x08.Request\x1a\t.Response\"\x00\x12\"\n\tSummarize\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mixtral_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST'].fields_by_name['max_tokens']._options = None
  _globals['_REQUEST'].fields_by_name['max_tokens']._serialized_options = b'\030\001'
  _globals['_ID']._serialized_start=17
  _globals['_ID']._serialized_end=60
  _globals['_REQUEST']._serialized_start=62
  _globals['_REQUEST']._serialized_end=147
  _globals['_RESPONSE']._serialized_start=149
  _globals['_RESPONSE']._serialized_end=209
  _globals['_CALLLLM']._serialized_start=211
  _globals['_CALLLLM']._serialized_end=326
# @@protoc_insertion_point(module_scope)
